export const TMDB_FETCH_MOVIES_BEGIN = 'TMDB_FETCH_MOVIES_BEGIN';
export const TMDB_FETCH_MOVIES_SUCCESS = 'TMDB_FETCH_MOVIES_SUCCESS';
export const TMDB_FETCH_MOVIES_FAILURE = 'TMDB_FETCH_MOVIES_FAILURE';
export const TMDB_FETCH_MOVIES_DISMISS_ERROR = 'TMDB_FETCH_MOVIES_DISMISS_ERROR';
export const TMDB_FETCH_SHOWS_BEGIN = 'TMDB_FETCH_SHOWS_BEGIN';
export const TMDB_FETCH_SHOWS_SUCCESS = 'TMDB_FETCH_SHOWS_SUCCESS';
export const TMDB_FETCH_SHOWS_FAILURE = 'TMDB_FETCH_SHOWS_FAILURE';
export const TMDB_FETCH_SHOWS_DISMISS_ERROR = 'TMDB_FETCH_SHOWS_DISMISS_ERROR';
